package com.org.testApi.payload;

import com.org.testApi.models.Currency;
import com.org.testApi.validation.ValidCurrency; // Added import for currency validation
import lombok.Data;
import lombok.EqualsAndHashCode;
import java.math.BigDecimal;
import java.time.LocalDate;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

@Data
@EqualsAndHashCode(callSuper = true)
public class FinancialTransactionPayload extends BasePayload {
    private Long id;
    
    @NotNull(message = "Le montant est obligatoire")
    @Positive(message = "Le montant doit être positif")
    private BigDecimal amount;
    
    @ValidCurrency
    private Currency currency;
    
    @NotNull(message = "La date de transaction est obligatoire")
    private LocalDate transactionDate;
    
    @Size(max = 100, message = "La description ne doit pas dépasser 100 caractères")
    private String description;
    
    @NotBlank(message = "Le type est obligatoire")
    private String type;
    
    @NotNull(message = "L'ID de l'association est obligatoire")
    private Long associationId;
    
    private Long activityId;
    private Long projectId;
    private Long categoryId;

    // Getters and setters will be generated by Lombok @Data annotation
    // Note: projectId peut être utilisé pour associer cette transaction à un projet existant.
    // Vous pouvez créer une transaction sans projet, puis l'associer à un projet ultérieurement.
}