package com.org.testApi.payload;

import lombok.Data;
import lombok.EqualsAndHashCode;
import java.math.BigDecimal;
import java.time.LocalDate;

@Data
@EqualsAndHashCode(callSuper = true)
public class FinancialTransactionPayload extends BasePayload {
    private Long id;
    private BigDecimal amount;
    private LocalDate transactionDate;
    private String description;
    private String type;
    private Long associationId;
    private Long activityId;
    private Long projectId;
    private Long categoryId;

    // Getters and setters will be generated by Lombok @Data annotation
}
