package com.org.testApi.payload;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
public class FinancialCategoryPayload extends BasePayload {
    private Long id;
    private String name;
    private String description;
    private String type;
    private Long associationId;

    // Getters and setters will be generated by Lombok @Data annotation
}
