package com.org.testApi.payload;

import lombok.Data;
import lombok.EqualsAndHashCode;
import java.math.BigDecimal;
import java.time.LocalDate;

@Data
@EqualsAndHashCode(callSuper = true)
public class LoanPayload extends BasePayload {
    private Long id;
    private Long memberId;
    private Long documentId;
    private Long loanTypeId;
    private BigDecimal amount;
    /**
     * Devise du montant du prêt.
     * Par défaut, CDF (Franc congolais) si non spécifiée.
     * Valeurs possibles : CDF, USD, EUR
     */
    private com.org.testApi.models.Currency currency;
    private BigDecimal interestRate;
    private BigDecimal penaltyRate;
    private LocalDate dueDate;
    private LocalDate repaymentDate;
    private BigDecimal amountRepaid;
    private String status;

    // Getters and setters will be generated by Lombok @Data annotation
}