package com.org.testApi.payload;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
public class MemberPayload extends BasePayload {
    private Long id;
    private Long userId;
    private String firstName;
    private String lastName;
    private String email;
    private String phone;
    private String address;
    private Long associationId;
    private String memberCode; // Ajout du code membre

    // Getters and setters will be generated by Lombok @Data annotation
}