package com.org.testApi.payload;

import com.org.testApi.models.MembershipFee;
import lombok.Data;
import lombok.EqualsAndHashCode;
import java.math.BigDecimal;
import java.time.LocalDate;

@Data
@EqualsAndHashCode(callSuper = true)
public class MembershipFeePayload extends BasePayload {
    private Long id;
    private Long memberId;
    private BigDecimal amount;
    private LocalDate paymentDate;
    private LocalDate startDate;
    private LocalDate endDate;
    private Long transactionId;
    private MembershipFee.PaymentMethod paymentMethod;
    private String reference;

    // Getters and setters will be generated by Lombok @Data annotation
}