package com.org.testApi.payload;

import lombok.Data;
import lombok.EqualsAndHashCode;
import java.time.LocalDate;

@Data
@EqualsAndHashCode(callSuper = true)
public class MemberRoleHistoryPayload extends BasePayload {
    private Long id;
    private Long memberId;
    private String role;
    private LocalDate startDate;
    private LocalDate endDate;
    private boolean isAdmin;

    // Getters and setters will be generated by Lombok @Data annotation
}
