package com.org.testApi.payload;

import lombok.Data;
import lombok.EqualsAndHashCode;
import java.time.LocalDate;
import java.util.List;

@Data
@EqualsAndHashCode(callSuper = true)
public class ProjectPayload extends BasePayload {
    private Long id;
    private String name;
    private String description;
    private LocalDate startDate;
    private LocalDate endDate;
    private Long associationId;
    private Long managerId;
    private List<Long> activityIds;
    private List<Long> memberIds;
    private List<Long> transactionIds;
    private String status;

    // Getters and setters will be generated by Lombok @Data annotation
    // Note: transactionIds doit contenir les IDs des transactions financières existantes
    // qui seront associées à ce projet lors de sa création. Vous pouvez créer un projet
    // sans transactions, puis ajouter des transactions ultérieurement.
}