package com.org.testApi.payload;

import lombok.Data;
import lombok.EqualsAndHashCode;
import java.time.LocalDate;

@Data
@EqualsAndHashCode(callSuper = true)
public class ProjectMemberPayload extends BasePayload {
    private Long id;
    private Long projectId;
    private Long memberId;
    private String roleInProject;
    private LocalDate joinDate;
    private LocalDate leaveDate;

    // Getters and setters will be generated by Lombok @Data annotation
}
