package com.org.testApi.payload;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
public class RolePayload extends BasePayload {
    private Integer id;
    private String name;
    private String description;

    // Getters and setters will be generated by Lombok @Data annotation
}
