package com.org.testApi.payload;

import lombok.Data;
import lombok.EqualsAndHashCode;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

@Data
@EqualsAndHashCode(callSuper = true)
public class RolePayload extends BasePayload {
    private Integer id;
    
    @NotNull(message = "Role name is required")
    @Size(max = 20, message = "Role name must not exceed 20 characters")
    private String name;
    
    @Size(max = 20, message = "Description must not exceed 20 characters")
    private String description;

    // Getters and setters will be generated by Lombok @Data annotation
}