package com.org.testApi.payload;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
public class UserPayload extends BasePayload {
    private Long id;
    private String username;
    private String email;
    private String password;
    private Boolean enabled;
    private Long roleId;
    private String firstName;
    private String lastName;
    private String phoneNumber;

    // Getters and setters will be generated by Lombok @Data annotation
}
